image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
secrets:
- 7562c2fd-1ce8-4e3a-be2b-8ede538f9bfa
sources:
- git@git.sr.ht:~emceeaich/gemini.emmas.site
environment:
  site: gemini.emmas.site
  repo: gemini.emmas.site
tasks:
- package: |
    cd $repo
    tar -C _gemini -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site -p GEMINI site.tar.gz
    